name: Auto Build and Commit Dist

on:
  push:
    branches:
      - main  # replace with the name of your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # you can specify a Node.js version here

    - name: Install dependencies
      run: yarn install

    - name: Run build
      run: yarn build  # assumes you have a 'build' script in your package.json

    - name: Commit and Push dist folder
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -f dist/
        git commit -m "Auto commit of built dist directory"
        git push
        
